https://community.topcoder.com/stat?c=problem_statement&pm=6680
tanmesh/topcoder_code pull request #6
Opened 2018-01-10 12:58 UTC by tanmesh

2018-01-10 13:05 UTC, tanmesh commented on SRM 325/RGBStreet.cpp
> +        cout << endl;
debugging...

2018-01-10 13:07 UTC, nilmish requested changes

2018-01-10 13:07 UTC, nilmish commented on SRM 325/RGBStreet.cpp
> +        int &res = dp[i];
There are 2 states -- current index and what was the last character you kept. So, its a 2D dp.

2018-01-10 13:07 UTC, nilmish commented on SRM 325/RGBStreet.cpp
> +    int cvt_strto_int(string s) {
Write complete - convertStringToInt. Also, either use camel case or snake case but not both.

2018-01-10 13:07 UTC, nilmish commented on SRM 325/RGBStreet.cpp
> +    vector<vector<int> > extractPrices(vector<string> houses) {
Here you have used `extractPrices` which is in camel case and above you have used  `cvt_strto_int ` in snake case.

2018-01-10 16:55 UTC, nilmish requested changes

2018-01-10 16:55 UTC, nilmish commented on SRM 325/RGBStreet.cpp
> +    int ConvertStringToInt(string s) {
in the camel case first letter is always small. it should be like `convertStringToInt `

2018-01-10 16:55 UTC, nilmish commented on SRM 325/RGBStreet.cpp
> +    vector<vector<int> > ExtractPrices(vector<string> houses) {
it should be `extractPrices `

2018-01-10 16:55 UTC, nilmish commented on SRM 325/RGBStreet.cpp
> +        int n =  s.length();
better name would be `len` rather than `n`

2018-01-10 16:55 UTC, nilmish commented on SRM 325/RGBStreet.cpp
> +    int f(int i, int& last, char colour, vector<string>& houses, vector< vector< int> >& prices) {
Why do you need to pass `last` here? `last` can be inferred from `houses.size()`

2018-01-10 16:55 UTC, nilmish commented on SRM 325/RGBStreet.cpp
> +int dp[100][100];
this could be dp[100][4] as the colour has only 4 possible values: empty, red, green, blue

2018-01-10 16:55 UTC, nilmish commented on SRM 325/RGBStreet.cpp
> +        int &res = dp[i][colour];
Convert `colour` to integer before indexing into array dp

2018-01-11 12:54 UTC, nilmish commented on SRM 325/RGBStreet.cpp
> +    int f(int i, int colour, vector<string>& houses, vector< vector< int> >& prices) {
`houses` is redundant here.

2018-01-11 12:56 UTC, tanmesh commented on SRM 325/RGBStreet.cpp
> +    int f(int i, int colour, vector<string>& houses, vector< vector< int> >& prices) {
bt then i have to pass "last"...

2018-01-16 17:11 UTC, nilmish requested changes

2018-01-16 17:11 UTC, nilmish commented on SRM 325/RGBStreet.cpp
> +    int f(int i, int colour, vector<string>& houses, vector< vector< int> >& prices) {
last = prices.size()

2018-01-17 17:37 UTC, nilmish requested changes

2018-01-17 17:37 UTC, nilmish commented on SRM 325/RGBStreet.cpp
> +                if(previousHousePaint == -1) {
You can combine this case with below. Just recur on the subproblem for the cases where `previousHousePaint ` is different. Like 
```
if(previousHousePaint != 0) {
    // use color 0 at this position
}

if(previousHousePaint != 1) {
    // use color 1 at this position
}

if(previousHousePaint != 2) {
    // use color 2 at this position
}
```

2018-01-18 19:41 UTC, nilmish requested changes

2018-01-18 19:41 UTC, nilmish commented on SRM 325/RGBStreet.cpp
> +            ans = prices[i][0] + min(minPrice(i+1, 0, housesCnt, prices), ans);
this is incorrect. it should be ` ans = min(ans, prices[i][0] + minPrice(i+1, 0, housesCnt, prices));`

2018-01-18 19:41 UTC, nilmish commented on SRM 325/RGBStreet.cpp
> +            ans = prices[i][1] + min(minPrice(i+1, 1, housesCnt, prices), ans);
same as above

2018-01-18 20:16 UTC, nilmish approved these changes

2018-01-18 20:19 UTC, merged